### ISSUE TITLE
您好，请问如何调整训练与评估的图像输入尺寸（input_size）？

### ISSUE THREAD

**Issue by homxxx** [DetectionTeamUCAS/Cascade_FPN_Tensorflow#15]

**Comment by yangxue0827** [comment]
IMG_SHORT_SIDE_LEN in cfgs.py

**Comment by homxxx** [comment]
谢谢，请问IMG_MAX_LENGTH = 1333
是代表什么意思呢

**Comment by yangxue0827** [comment]
这两个参数的意思是将图像的短边设置成IMG_SHORT_SIDE_LEN，长边同比例缩放但最大不超过IMG_MAX_LENGTH

**Comment by homxxx** [comment]
是否是 如果我想要input_size=(512,512,3) 那么可以设置为IMG_SHORT_SIDE_LEN = 512 ；IMG_MAX_LENGTH = 512； ？谢谢

**Comment by yangxue0827** [comment]
可以

**Comment by homxxx** [comment]
thanks






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DetectionTeamUCAS/Cascade_FPN_Tensorflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 下午2:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DetectionTeamUCAS/Cascade_FPN_Tensorflow] 您好，请问如何调整训练与评估的图像输入尺寸（input_size）？ (#15)





 
可以
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
