### ISSUE TITLE
关于voc2007 map问题

### ISSUE THREAD

**Issue by homxxx** [DetectionTeamUCAS/Cascade_FPN_Tensorflow#16]
请问使用voc2007训练集训练 ，并用voc2007测试集 进行eva。为什么resnet101 训练后的结果map只有50几。除了修改了batch size=6 和数据集配置 ；其余的都是cfg文件默认的参数；

**Comment by yangxue0827** [comment]
不支持bs>1

**Comment by homxxx** [comment]
voc2007test跑了很多次都是map=71% 左右 ，请问这个指标正常嘛？

**Comment by yangxue0827** [comment]
![image](https://user-images.githubusercontent.com/29257168/134292792-5794c963-5dd3-45dd-ae36-01e438578569.png)
是yong de是用的这个pretrain model吗

**Comment by homxxx** [comment]
不是的，上面那个 resnet101_v1

**Comment by yangxue0827** [comment]
cfgs.py中有个参数改成NET_NAME = 'resnet50_v1d'，然后下载我推荐的新权重试试，我不太记得readme里的结果是哪个pretrain model跑出来的了

**Comment by yangxue0827** [comment]
一般NET_NAME = 'resnet50_v1d'
这个效果会好挺多

**Comment by homxxx** [comment]
好的，请问有没有resnet101的选择？效果好点的话

**Comment by yangxue0827** [comment]
这个repo我好像没有跑过voc，所以你的71不清楚正不正常，但感觉是偏低的，因为FPN好像都不止这个性能，推荐使用新的pretrain weight

**Comment by yangxue0827** [comment]
有的，改成resnet101_v1d就行，只要下载了对应的pretrain weight

**Comment by homxxx** [comment]
好的 我试一下

**Comment by homxxx** [comment]
你好，换了resnet101_v1d，十六万轮后map还是71%
![image](https://user-images.githubusercontent.com/59168249/134514922-30970046-c5b3-42e7-9d15-a327d818882f.png)

**Comment by yangxue0827** [comment]
那可能真的是这样的效果，如果你跑voc那可以用[FPN](https://github.com/DetectionTeamUCAS/FPN_Tensorflow)那个repo，这个repo可能在coco上效果好。

**Comment by homxxx** [comment]
ok了解! 主要是想跑Cascade_FPN这个

**Comment by homxxx** [comment]
您好，请问这些train文件的区别是什么？我一直都是multi_gpu_train.py
![image](https://user-images.githubusercontent.com/59168249/136650544-600f2d57-9acb-42d5-8122-fbd1fa451728.png)

**Comment by homxxx** [comment]
会不会问题出在这里
