### ISSUE TITLE
coco.odgt

### ISSUE THREAD

**Issue by 0fine0** [DetectionTeamUCAS/Cascade_FPN_Tensorflow#4]
I wanna use the coco dataset for training, however I can't find the coco.odgt on any website.
Or how can I convert the JSON files into odgt files?

Thank you for any help!

**Comment by yangxue0827** [comment]
link：https://pan.baidu.com/s/156ibBsTI5sMOo6LIuFVreg 
password：zjvg 
@0fine0

**Comment by 0fine0** [comment]
Thank you for sharing the odgt files, it's really helpful !!!

Could you please give out the python file which is used to convert coco files into odgt files? I want to change all the coco files into odgt files and use them to train networks. Thank you anyway!
@yangxue0827
