### ISSUE TITLE
关于学习率的问题

### ISSUE THREAD

**Issue by LLLhp** [DetectionTeamUCAS/Cascade_FPN_Tensorflow#7]
大神您好！非常感谢你们的工作和分享！我最近在用你们的代码训练自己的无人机影像数据集，然后关于学习率有个问题想请问您：我注意到您在tools/train.py中写了warmup_and_cosine_lr函数，也即使用“预热+余弦衰减”的组合对吧，可是我在训练过程观察学习率的变化，发现其在前面是线性余弦的变化、后面是类似于分段常数衰减的方式，如下图。请问这个现象正常吗？还是由于我操作不当造成的呢？期待您在百忙之中的回复，感谢！
![图片1](https://user-images.githubusercontent.com/48044991/69613994-6b8b6a80-106d-11ea-9188-774dd94b1673.png)

**Comment by yangxue0827** [comment]
这个功能在multi_gpu_train_warmup_cosine.py

**Comment by LLLhp** [comment]
噢噢，是这个样子的啊。好的，谢谢大神！

**Comment by LLLhp** [comment]
Thank you very much! I am a newbie in this research direction, thank you for your sharing and patient answers.

在 2019-12-03 00:51:31，"yangxue" <notifications@github.com> 写道：


Closed #7.
